services:
  - type: web
    name: upi-finanalyzer
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: deployment
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
    healthCheckPath: /